# Global configuration for all services
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: swiftlogistics
    password: logistics123
    virtual-host: /
    connection-timeout: 15000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

---
# Docker Profile - Global for all services
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/