# services/tracking-service/src/main/resources/application.yml
server:
  port: 8084

spring:
  application:
    name: tracking-service

  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.config.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.config.DiscoveryClientOptionalArgsConfiguration
      - org.springframework.cloud.config.client.ConfigClientAutoConfiguration
      - org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration
      - org.springframework.cloud.commons.util.UtilAutoConfiguration
      - org.springframework.cloud.context.refresh.ContextRefresherAutoConfiguration
      - org.springframework.cloud.context.scope.refresh.RefreshScopeAutoConfiguration

  # Disable Spring Cloud Config
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

  # Database configuration
  datasource:
    url: jdbc:h2:mem:trackingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  # Redis configuration
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Disable Eureka
eureka:
  client:
    enabled: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.swiftlogistics.tracking: DEBUG
    org.springframework.web: DEBUG