# infrastructure/api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # Integration Service API Routes - FINAL FIX: NO StripPrefix
        - id: integration-service-api
          uri: lb://integration-service
          predicates:
            - Path=/api/integration/**
            # NO FILTERS - Pass the full path /api/integration/** to the service

        # Mock System Routes - These work fine
        - id: integration-service-mock
          uri: lb://integration-service
          predicates:
            - Path=/mock/**
            # No StripPrefix - keep full path

        # Order Service Routes - Order service needs /api stripped
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
            # NO FILTERS - Order service controller already has /api/orders mapping

        # Tracking Service Routes
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**
            # NO FILTERS - Let service handle the full path

        # Driver Service Routes
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
          # NO FILTERS - Let service handle the full path

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{HH:mm:ss} [API-Gateway] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

# Actuator endpoints for debugging
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    gateway:
      enabled: true

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/