server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Order Service Routes
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        # Integration Service Routes
        - id: integration-service
          uri: lb://integration-service
          predicates:
            - Path=/api/integration/**
          filters:
            - StripPrefix=0

        # Tracking Service Routes
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**
          filters:
            - StripPrefix=0

        # Driver Service Routes
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=0

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes,gateway

---
# Docker profile
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/