-- services/order-service/src/main/resources/data.sql
-- Sample Clients (Fixed column names)
INSERT INTO clients (client_id, company_name, contact_person, email, phone_number, address, active, created_at) VALUES
                                                                                                                    ('CLIENT-001', 'TechMart Electronics', 'John Silva', 'john@techmart.lk', '+94771234567', 'No 123, Galle Road, Colombo 03', true, CURRENT_TIMESTAMP),
                                                                                                                    ('CLIENT-002', 'Fashion Hub', 'Sarah Fernando', 'sarah@fashionhub.lk', '+94772345678', 'No 456, Kandy Road, Nugegoda', true, CURRENT_TIMESTAMP),
                                                                                                                    ('CLIENT-003', 'Book Paradise', 'Michael Perera', 'michael@bookparadise.lk', '+94773456789', 'No 789, Main Street, Kandy', true, CURRENT_TIMESTAMP),
                                                                                                                    ('CLIENT-004', 'Green Groceries', 'Priya Jayawardena', 'priya@greengroceries.lk', '+94774567890', 'No 321, Temple Road, Maharagama', true, CURRENT_TIMESTAMP),
                                                                                                                    ('CLIENT-005', 'Sports Zone', 'David Rajapaksa', 'david@sportszone.lk', '+94775678901', 'No 654, Baseline Road, Colombo 07', true, CURRENT_TIMESTAMP);

-- Sample Orders for demonstration
INSERT INTO orders (order_number, client_id, pickup_address, delivery_address, package_description, status, priority, created_at, updated_at) VALUES
                                                                                                                                                  ('ORD-DEMO-001', 'CLIENT-001', 'TechMart Warehouse, Kelaniya', '123 Lake Road, Nugegoda', 'Laptop - Dell Inspiron 15', 'PROCESSING', 'STANDARD', DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP)),
                                                                                                                                                  ('ORD-DEMO-002', 'CLIENT-002', 'Fashion Hub Store, Nugegoda', '456 Flower Road, Colombo 07', 'Designer Dress - Size M', 'IN_TRANSIT', 'EXPRESS', DATEADD('HOUR', -4, CURRENT_TIMESTAMP), DATEADD('MINUTE', -30, CURRENT_TIMESTAMP)),
                                                                                                                                                  ('ORD-DEMO-003', 'CLIENT-003', 'Book Paradise, Kandy', '789 School Lane, Matale', 'Educational Books - 5 items', 'DELIVERED', 'STANDARD', DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -2, CURRENT_TIMESTAMP)),
                                                                                                                                                  ('ORD-DEMO-004', 'CLIENT-004', 'Green Groceries Warehouse, Maharagama', '321 New Road, Panadura', 'Fresh Vegetables - 2kg', 'READY_FOR_DELIVERY', 'URGENT', DATEADD('HOUR', -3, CURRENT_TIMESTAMP), DATEADD('MINUTE', -10, CURRENT_TIMESTAMP)),
                                                                                                                                                  ('ORD-DEMO-005', 'CLIENT-005', 'Sports Zone, Colombo 07', '654 Station Road, Mount Lavinia', 'Cricket Equipment Set', 'SUBMITTED', 'STANDARD', DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), DATEADD('MINUTE', -30, CURRENT_TIMESTAMP));