-- services/driver-service/src/main/resources/data.sql
-- Sample Drivers for SwiftLogistics
INSERT INTO drivers (driver_id, full_name, email, phone_number, license_number, vehicle_type, vehicle_number, status, password, current_latitude, current_longitude, last_location_update, total_deliveries, completed_deliveries, failed_deliveries, rating, created_at, last_login_at, active, verified) VALUES
                                                                                                                                                                                                                                                                                                               ('DRV-001', 'Kasun Perera', 'kasun.perera@swift.lk', '+94771234567', 'B1234567', 'MOTORCYCLE', 'CAB-1234', 'AVAILABLE', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.9271, 79.8612, CURRENT_TIMESTAMP, 150, 142, 8, 4.7, DATEADD('DAY', -30, CURRENT_TIMESTAMP), DATEADD('HOUR', -2, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-002', 'Sanduni Fernando', 'sanduni.fernando@swift.lk', '+94772345678', 'B2345678', 'CAR', 'CAR-5678', 'BUSY', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.9319, 79.8478, CURRENT_TIMESTAMP, 98, 91, 7, 4.3, DATEADD('DAY', -25, CURRENT_TIMESTAMP), DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-003', 'Chaminda Silva', 'chaminda.silva@swift.lk', '+94773456789', 'B3456789', 'VAN', 'VAN-9876', 'AVAILABLE', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.9147, 79.9729, CURRENT_TIMESTAMP, 87, 82, 5, 4.6, DATEADD('DAY', -20, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-004', 'Priya Jayawardena', 'priya.jayawardena@swift.lk', '+94774567890', 'B4567890', 'SCOOTER', 'SCO-4321', 'ON_BREAK', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.8649, 79.8997, DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), 64, 59, 5, 4.2, DATEADD('DAY', -15, CURRENT_TIMESTAMP), DATEADD('HOUR', -3, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-005', 'Nuwan Rajapaksa', 'nuwan.rajapaksa@swift.lk', '+94775678901', 'B5678901', 'TRUCK', 'TRK-1111', 'OFFLINE', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', NULL, NULL, NULL, 45, 40, 5, 4.0, DATEADD('DAY', -12, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-006', 'Amara Wickramasinghe', 'amara.wickrama@swift.lk', '+94776789012', 'B6789012', 'MOTORCYCLE', 'CAB-2345', 'AVAILABLE', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.9919, 79.9753, CURRENT_TIMESTAMP, 123, 118, 5, 4.8, DATEADD('DAY', -18, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-007', 'Tharushi Mendis', 'tharushi.mendis@swift.lk', '+94777890123', 'B7890123', 'CAR', 'CAR-6789', 'BUSY', '$2a$10$N.kmUCYE1kSwezhkd7VQyOj/3pC7LkA7vF.0/eBMk/uKXLK5bP6Cu', 6.8905, 79.8563, CURRENT_TIMESTAMP, 76, 72, 4, 4.5, DATEADD('DAY', -10, CURRENT_TIMESTAMP), DATEADD('MINUTE', -15, CURRENT_TIMESTAMP), true, true),
                                                                                                                                                                                                                                                                                                               ('DRV-008', 'Rohan de Silva', 'rohan.desilva@swift.lk', '+94778901234', 'B8901234', 'BICYCLE', 'BIC-0001', 'UNAVAILABLE', '$2a$12$7hCePs.opsrXT5aS3aY48OKH2Bo1PIXYt8yxHDBrGBpzeOya9Vc1C', NULL, NULL, NULL, 32, 28, 4, 3.9, DATEADD('DAY', -8, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), true, false);

-- Sample Deliveries (some active, some completed)
INSERT INTO deliveries (order_number, client_id, driver_id, pickup_address, delivery_address, package_description, priority, status, scheduled_date, assigned_at, picked_up_at, delivered_at, recipient_name, recipient_phone, special_instructions, route_sequence, route_id, created_at, updated_at) VALUES
-- Active deliveries for Driver 1 (Kasun)
('ORD-ACT-001', 'CLIENT-001', 1, 'TechMart Warehouse, Kelaniya', '123 Lake Road, Nugegoda', 'Laptop - Dell Inspiron 15', 'EXPRESS', 'EN_ROUTE_DELIVERY', CURRENT_TIMESTAMP, DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP), NULL, 'John Silva', '+94771111111', 'Call before delivery', 1, 'ROUTE-001', DATEADD('HOUR', -2, CURRENT_TIMESTAMP), DATEADD('MINUTE', -30, CURRENT_TIMESTAMP)),
('ORD-ACT-002', 'CLIENT-002', 1, 'Fashion Hub Store, Nugegoda', '456 Flower Road, Colombo 07', 'Designer Dress - Size M', 'STANDARD', 'ASSIGNED', DATEADD('HOUR', 1, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP), NULL, NULL, 'Sarah Fernando', '+94772222222', 'Fragile item', 2, 'ROUTE-001', DATEADD('HOUR', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP)),

-- Active deliveries for Driver 2 (Sanduni)
('ORD-ACT-003', 'CLIENT-003', 2, 'Book Paradise, Kandy', '789 School Lane, Matale', 'Educational Books - 5 items', 'URGENT', 'PICKED_UP', CURRENT_TIMESTAMP, DATEADD('HOUR', -3, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP), NULL, 'Michael Perera', '+94773333333', 'Handle with care', 1, 'ROUTE-002', DATEADD('HOUR', -3, CURRENT_TIMESTAMP), DATEADD('HOUR', -1, CURRENT_TIMESTAMP)),

-- Active deliveries for Driver 7 (Tharushi)
('ORD-ACT-004', 'CLIENT-004', 7, 'Green Groceries Warehouse, Maharagama', '321 New Road, Panadura', 'Fresh Vegetables - 2kg', 'EXPRESS', 'AT_PICKUP', CURRENT_TIMESTAMP, DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), NULL, NULL, 'Priya Jayawardena', '+94774444444', 'Keep refrigerated', 1, 'ROUTE-007', DATEADD('MINUTE', -45, CURRENT_TIMESTAMP), DATEADD('MINUTE', -15, CURRENT_TIMESTAMP)),

-- Completed deliveries (for statistics)
('ORD-COMP-001', 'CLIENT-001', 1, 'TechMart Warehouse, Kelaniya', '111 Main Street, Colombo 05', 'Mobile Phone - Samsung Galaxy', 'STANDARD', 'DELIVERED', DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -18, CURRENT_TIMESTAMP), 'Alex Johnson', '+94775555555', NULL, 1, 'ROUTE-COMP-001', DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -18, CURRENT_TIMESTAMP)),
('ORD-COMP-002', 'CLIENT-002', 3, 'Fashion Hub Store, Nugegoda', '222 Galle Road, Mount Lavinia', 'Shoes - Nike Air Max', 'EXPRESS', 'DELIVERED', DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -12, CURRENT_TIMESTAMP), 'Emma Wilson', '+94776666666', 'Try before accepting', 2, 'ROUTE-COMP-002', DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('HOUR', -12, CURRENT_TIMESTAMP)),
('ORD-COMP-003', 'CLIENT-005', 6, 'Sports Zone, Colombo 07', '333 Kandy Road, Kadawatha', 'Cricket Bat - MRF Genius', 'STANDARD', 'DELIVERED', DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), 'David Rajapaksa', '+94777777777', NULL, 1, 'ROUTE-COMP-003', DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP)),

-- Failed deliveries (for statistics)
('ORD-FAIL-001', 'CLIENT-003', 4, 'Book Paradise, Kandy', '444 Temple Road, Kegalle', 'Academic Textbooks - 3 items', 'STANDARD', 'FAILED', DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP), NULL, 'Lisa Brown', '+94778888888', 'Deliver after 6 PM', 3, 'ROUTE-FAIL-001', DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP));

-- Update delivery references in drivers table (this is handled by JPA relationships, but for completeness)
-- The deliveries are linked via foreign key driver_id